services:
  cs2:
    image: joedwards32/cs2
    container_name: cs2
    hostname: cs2
    restart: unless-stopped
    labels:
      - "game-admin-panel.enabled=true"
      - "game-admin-panel.game=cs2"
    volumes:
      - cs2:/home/steam/cs2-dedicated/
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  cs2:
